#!/bin/bash
# publish-blog-post.sh - Publish blog post to GitHub Pages and syndication platforms
# Usage: ./scripts/publish-blog-post.sh <post_file> [--no-github] [--no-syndication]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
LOG_FILE="$REPO_ROOT/logs/publishing.log"

# Ensure log directory exists
mkdir -p "$REPO_ROOT/logs"

# Logging function
log_message() {
  echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

# Parse arguments
POST_FILE="${1:-}"
PUBLISH_GITHUB=true
PUBLISH_SYNDICATION=true

if [ -z "$POST_FILE" ]; then
  log_message "❌ Usage: $0 <post_file> [--no-github] [--no-syndication]"
  exit 1
fi

if [ ! -f "$POST_FILE" ]; then
  log_message "❌ Post file not found: $POST_FILE"
  exit 1
fi

for arg in "$@"; do
  case $arg in
    --no-github) PUBLISH_GITHUB=false ;;
    --no-syndication) PUBLISH_SYNDICATION=false ;;
  esac
done

log_message "🚀 Publishing Pipeline Started"
log_message "📄 Post: $POST_FILE"

# Extract metadata from frontmatter
TITLE=$(grep "^title:" "$POST_FILE" | sed 's/^title: *"\?\(.*\)"\?$/\1/' | head -1)
SLUG=$(grep "^slug:" "$POST_FILE" | sed 's/^slug: *//g' | head -1)
DATE=$(grep "^date:" "$POST_FILE" | sed 's/^date: *//g' | head -1)

log_message "📌 Title: $TITLE"
log_message "📅 Date: $DATE"
log_message "🔖 Slug: $SLUG"

# Step 1: GitHub Pages (main publishing platform)
if [ "$PUBLISH_GITHUB" = true ]; then
  log_message ""
  log_message "📤 Publishing to GitHub Pages..."
  
  # Verify we're in a git repo
  if ! git rev-parse --git-dir > /dev/null 2>&1; then
    log_message "❌ Not in a git repository"
    exit 1
  fi
  
  # Change status from draft to published
  sed -i.bak 's/status: draft/status: published/g' "$POST_FILE"
  rm -f "$POST_FILE.bak"
  
  # Stage the post
  git add "$POST_FILE"
  
  # Create commit
  COMMIT_MSG="📝 Publish: $TITLE"
  if git commit -m "$COMMIT_MSG" 2>/dev/null; then
    log_message "✅ Committed: $COMMIT_MSG"
  else
    log_message "⚠️  Already staged or no changes"
  fi
  
  # Push to GitHub
  if git push origin main 2>/dev/null; then
    log_message "✅ Pushed to GitHub"
    log_message "🌐 GitHub Pages will rebuild automatically"
  else
    log_message "⚠️  Push failed - verify GitHub credentials"
  fi
fi

# Step 2: Syndication (Dev.to, Medium, Twitter)
if [ "$PUBLISH_SYNDICATION" = true ]; then
  log_message ""
  log_message "🔗 Publishing to syndication platforms..."
  
  # Dev.to (if API key is set)
  if [ -n "$DEVTO_API_KEY" ]; then
    log_message "  📰 Dev.to..."
    if bash "$SCRIPT_DIR/publish-to-devto.sh" "$POST_FILE" 2>/dev/null; then
      log_message "  ✅ Dev.to published"
    else
      log_message "  ⚠️  Dev.to publishing skipped (API key or network issue)"
    fi
  fi
  
  # Medium (if API key is set)
  if [ -n "$MEDIUM_TOKEN" ]; then
    log_message "  📰 Medium..."
    if bash "$SCRIPT_DIR/publish-to-medium.sh" "$POST_FILE" 2>/dev/null; then
      log_message "  ✅ Medium published"
    else
      log_message "  ⚠️  Medium publishing skipped"
    fi
  fi
  
  # Substack (if API key is set)
  if [ -n "$SUBSTACK_API_KEY" ]; then
    log_message "  📬 Substack..."
    if bash "$SCRIPT_DIR/publish-to-substack.sh" "$POST_FILE" 2>/dev/null; then
      log_message "  ✅ Substack published"
    else
      log_message "  ⚠️  Substack publishing skipped"
    fi
  fi
  
  # Twitter/X (if credentials are set)
  if [ -n "$TWITTER_BEARER_TOKEN" ]; then
    log_message "  🐦 Twitter/X..."
    if bash "$SCRIPT_DIR/publish-to-twitter.sh" "$POST_FILE" 2>/dev/null; then
      log_message "  ✅ Twitter thread posted"
    else
      log_message "  ⚠️  Twitter posting skipped"
    fi
  fi
fi

# Step 3: Update blog metadata
log_message ""
log_message "📊 Updating metadata..."

PUBLISH_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)
METADATA_JSON="{
  \"slug\": \"$SLUG\",
  \"title\": \"$TITLE\",
  \"published_date\": \"$DATE\",
  \"published_at\": \"$PUBLISH_TIME\",
  \"url\": \"https://ApexCrispWave.github.io/ai-research-blog/$DATE/$SLUG/\",
  \"status\": \"published\"
}"

# Append to publishing log
echo "$METADATA_JSON" >> "$REPO_ROOT/logs/published-posts.json"
log_message "✅ Metadata recorded"

# Step 4: Generate/update RSS
log_message ""
log_message "🔄 Updating RSS feed..."

# Note: Jekyll with jekyll-feed will auto-generate RSS
# This is just a confirmation that the process continues
if [ -f "$REPO_ROOT/_config.yml" ]; then
  log_message "✅ RSS feed will be auto-generated by Jekyll"
else
  log_message "⚠️  _config.yml not found - RSS may not update"
fi

log_message ""
log_message "✨ Publishing pipeline complete!"
log_message ""
echo "Post Details:"
echo "  Title: $TITLE"
echo "  URL: https://ApexCrispWave.github.io/ai-research-blog/$DATE/$SLUG/"
echo "  Published: $PUBLISH_TIME"
echo ""
echo "Next steps:"
echo "  1. Visit GitHub repo to confirm push"
echo "  2. Check GitHub Pages site (takes 1-2 min to rebuild)"
echo "  3. Verify syndication posts appeared on platforms"
echo "  4. Share on social media if not automated"
